import { PortfolioConfig } from './configTypes';

export const defaultConfig: PortfolioConfig = {
  version: '1.0.0',
  personal: {
    name: 'VISHESH CHAWAN',
    titleLine1: 'AI & Backend Developer',
    location: 'Hyderabad, India',
    email: 'vishesh.chawan1@gmail.com',
    phone: '+91 8340867155',
    linkedinUrl: 'https://linkedin.com/in/visheshchawan',
    githubUrl: 'https://github.com/visheshchawan',
    statusBadge: 'OPEN TO OPPORTUNITIES',
  },
  hero: {
    description: 'AI & Backend Developer skilled in LLM engineering, RAG architectures, and complex backend systems. Currently pursuing B.Tech in CSE (Data Science) with a history of hackathon wins and scalable deployments.',
    roles: ['AI Developer', 'Backend Developer', 'LLM Engineer', 'RAG Architect'],
    stats: [
      { id: 'stat-1', number: '3+', label: 'Major Projects' },
      { id: 'stat-2', number: '25%', label: 'RAG Accuracy Boost' },
      { id: 'stat-3', number: '40%', label: 'Deployment Time Reduced' },
      { id: 'stat-4', number: '1st', label: 'Hackathon Win' },
    ],
  },
  projects: [
    {
      id: 'proj-1',
      name: 'ArtYatra',
      subtitle: 'AI-Powered Indian Art Exploration',
      description: 'Built an AI web application classifying 8 distinct Indian art styles using Gemini API and TensorFlow. Real-time art exploration via Leaflet maps, backed by the Swecha Corpus. Integrated model analytics dashboards for interpretability.',
      githubUrl: 'https://github.com/visheshchawan',
      liveUrl: '#',
      metrics: [
        { id: 'm-1', value: '<1.2s', label: 'LATENCY' },
        { id: 'm-2', value: '500+', label: 'SAMPLES TESTED' },
        { id: 'm-3', value: '99.9%', label: 'UPTIME' },
        { id: 'm-4', value: '+35%', label: 'ENGAGEMENT' },
      ],
      techStack: ['Next.js', 'Express', 'PostgreSQL', 'Gemini API', 'TensorFlow', 'Docker', 'Vercel', 'Leaflet.js'],
    },
    {
      id: 'proj-2',
      name: 'IndiaConnect',
      subtitle: 'Nationwide Community Platform',
      description: 'Scalable collaboration platform for 1,200+ students. CI/CD automation with GitHub Actions. Secure authentication system with session management.',
      githubUrl: 'https://github.com/visheshchawan',
      liveUrl: '#',
      metrics: [
        { id: 'm-5', value: '1,200+', label: 'USERS' },
        { id: 'm-6', value: '-40%', label: 'DEPLOY TIME' },
      ],
      techStack: ['Next.js', 'Express', 'PostgreSQL', 'Drizzle', 'Docker', 'GitHub Actions'],
    },
    {
      id: 'proj-3',
      name: 'SEBI EduFin',
      subtitle: 'AI × EdTech Analytics',
      description: 'AI-powered financial learning platform with interactive BI dashboards. Optimized caching for sub-second load times across complex D3.js visualizations.',
      githubUrl: 'https://github.com/visheshchawan',
      liveUrl: '#',
      metrics: [
        { id: 'm-7', value: '+35%', label: 'INSIGHT GAIN' },
        { id: 'm-8', value: 'Fast', label: 'CACHE LAYER' },
      ],
      techStack: ['React', 'FastAPI', 'D3.js', 'Pandas'],
    },
  ],
  experience: [
    {
      id: 'exp-1',
      role: 'AI DEVELOPER INTERN',
      company: 'Swecha Telangana @ Viswam AI · Hyderabad, India',
      dateRange: 'Jul–Oct 2025',
      bullets: [
        'Built LLM-based microservices using Gemini API, FAISS, and Chroma for intelligent doc retrieval',
        'Applied RAG pipelines + prompt-tuning → +25% improvement in retrieval accuracy',
        'Deployed MLOps workflows for model lifecycle management using Docker',
        'Created REST APIs with authentication, logging, and analytics tracking',
        'Delivered TypeScript/Express APIs with evaluation systems + continuous delivery',
        'Cross-functional collaboration to integrate AI into production systems at scale'
      ],
      techStack: ['Python', 'FastAPI', 'Docker', 'Gemini API', 'FAISS', 'Chroma', 'RAG', 'LLMs', 'TypeScript', 'REST API'],
    },
    {
      id: 'exp-2',
      role: 'Sponsorship & External Relations Lead',
      company: 'College Event Committee',
      dateRange: '2023 – Present',
      bullets: [
        'Leading sponsorship efforts and external partnerships for college technical events',
        'Coordinating with industry partners and managing stakeholder communications',
        'Organizing large-scale tech events with cross-functional team collaboration'
      ],
      techStack: ['Leadership', 'Event Management', 'Stakeholder Relations'],
    },
  ],
  skills: {
    'Languages': ['Python', 'JavaScript/TypeScript', 'Java', 'SQL', 'C/C++'],
    'AI & Machine Learning': ['LLMs (OpenAI, Gemini)', 'RAG Pipelines', 'LangChain / LlamaIndex', 'Prompt Engineering', 'Hugging Face', 'Vector DBs (Chroma, Pinecone)', 'Ollama'],
    'Backend & Frameworks': ['FastAPI', 'Django', 'Express.js', 'Node.js', 'Next.js', 'React.js'],
    'Cloud & DevOps': ['Docker', 'Google Cloud Platform (GCP)', 'AWS', 'Vercel', 'Git / GitHub', 'CI/CD Pipelines'],
  },
  achievements: [
    {
      id: 'ach-1',
      rank: '1ST',
      title: 'Build4India Hackathon',
      subtitle: 'National Level',
      color: 'var(--accent-gold)',
      iconName: 'Trophy',
    },
    {
      id: 'ach-2',
      rank: '3RD',
      title: 'IBM × CognitivX Hackathon',
      subtitle: 'Enterprise AI',
      color: 'var(--text-secondary)',
      iconName: 'Medal',
    },
    {
      id: 'ach-3',
      rank: 'FINALIST',
      title: 'Buildathon — Nextwave × OpenAI',
      subtitle: 'State Recognition',
      color: 'var(--accent-tertiary)',
      iconName: 'Award',
    },
  ],
  certifications: [
    { id: 'cert-1', title: 'Programming Essentials in Python', issuer: 'Cisco' },
    { id: 'cert-2', title: 'The Complete Python Developer', issuer: 'Udemy' },
    { id: 'cert-3', title: 'Machine Learning Specialization', issuer: 'Coursera × Google AI' },
  ],
  theme: {
    presetName: 'Neural Noir',
    accentPrimary: '#00ffc8',
    accentSecondary: '#6d28d9',
    accentTertiary: '#f0abfc',
    bgVoid: '#010108',
    bgDeep: '#02020f',
    bgSurface: '#06061a',
    bgCard: '#0a0a20',
    textPrimary: '#f1f5f9',
    textSecondary: '#94a3b8',
    displayFont: 'Space Grotesk',
    monoFont: 'Fira Code',
    accentFont: 'Teko',
    glowIntensity: 0.35,
    chamferSize: 12,
  },
  animations: {
    masterEnabled: true,
    respectReducedMotion: true,
    bootEnabled: true,
    bootDuration: 2100, // Matching our sped up boot
    bootStyle: 'terminal',
    bootMessages: [
      '> INITIALIZING NEURAL INTERFACE...',
      '> LOADING IDENTITY MATRIX...',
      '> ESTABLISHING VISUAL CONNECTION...',
      '> SYSTEM READY.',
    ],
    cursor: {
      style: 'circle',
      primarySize: 12,
      ringSize: 48,
      ringLag: 0.1,
      color: 'accent',
      trailEnabled: true,
      trailLength: 5,
      blendMode: 'difference',
    },
    particles: {
      enabled: true,
      count: 120,
      size: 1.5,
      speed: 0.2,
      linesEnabled: true,
      lineDistance: 120,
      lineOpacity: 0.15,
      mouseInteraction: 'repel',
      mouseStrength: 0.3,
    },
  },
  sections: [
    { id: 'hero', type: 'hero', visible: true, order: 0, title: '', tagText: '', background: 'void' },
    { id: 'about', type: 'about', visible: true, order: 1, title: 'IDENTITY_MATRIX', tagText: '// 01 _ PROFILE_DATA', background: 'deep' },
    { id: 'skills', type: 'skills', visible: true, order: 2, title: 'TECHNICAL\nARSENAL', tagText: '// 02 _ CAPABILITIES', background: 'surface' },
    { id: 'experience', type: 'experience', visible: true, order: 3, title: 'WORK_HISTORY', tagText: '// 03 _ EXPERIENCE', background: 'deep' },
    { id: 'projects', type: 'projects', visible: true, order: 4, title: 'FEATURED\nPROJECTS', tagText: '// 04 _ DEPLOYMENTS', background: 'surface' },
    { id: 'recognition', type: 'recognition', visible: true, order: 5, title: 'CERTIFICATIONS', tagText: '// 05 _ RECOGNITION', background: 'deep' },
    { id: 'contact', type: 'contact', visible: true, order: 6, title: "LET'S BUILD", tagText: '// 06 _ INITIATE_COMMS', background: 'void' },
  ],
  advanced: {
    seoTitle: 'Vishesh Chawan | AI & Backend Developer',
    seoDescription: 'AI & Backend Developer skilled in LLM engineering, RAG architectures, and complex backend systems.',
  },
};
